services:
  book_rental:
    image: mysql:8.0
    container_name: book_rental_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: fc
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
      - ./docker/init:/docker-entrypoint-initdb.d

volumes:
  mysql-data: